//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_BackEnd_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anfrage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anfrage()
        {
            this.Kategorieanfrage = new HashSet<Kategorieanfrage>();
            this.Rechnung = new HashSet<Rechnung>();
        }
    
        public int id { get; set; }
        public int gast_id { get; set; }
        public System.DateTime datumVon { get; set; }
        public System.DateTime datumBis { get; set; }
        public System.DateTime datumAnfrage { get; set; }
        public Nullable<System.DateTime> datumBearbeitet { get; set; }
    
        public virtual Gast Gast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategorieanfrage> Kategorieanfrage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rechnung> Rechnung { get; set; }
    }
}
