//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_BackEnd_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gastlogin
    {
        public int id { get; set; }
        public int gast_id { get; set; }
        public int login_id { get; set; }
    
        public virtual Gast Gast { get; set; }
        public virtual Login Login { get; set; }
    }
}
