//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_BackEnd_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategorieausstattung
    {
        public int id { get; set; }
        public int ausstattung_id { get; set; }
        public int kategorie_id { get; set; }
        public byte anzahl { get; set; }
    
        public virtual Ausstattung Ausstattung { get; set; }
        public virtual Kategorie Kategorie { get; set; }
    }
}
