//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_BackEnd_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rechnung
    {
        public int id { get; set; }
        public int anfrage_id { get; set; }
        public decimal gesamtpreis { get; set; }
        public byte anzahlPersonen { get; set; }
        public byte anzahlNaechte { get; set; }
        public System.DateTime datumAktualisiert { get; set; }
    
        public virtual Anfrage Anfrage { get; set; }
    }
}
