//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_BackEnd_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rueckruf
    {
        public int id { get; set; }
        public string name { get; set; }
        public string telefon { get; set; }
        public string grund { get; set; }
        public System.DateTime datum_erhalten { get; set; }
        public Nullable<System.DateTime> datum_erledigt { get; set; }
    }
}
