//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_BackEnd_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Saison
    {
        public int id { get; set; }
        public string bezeichnung { get; set; }
        public byte monatVon { get; set; }
        public byte monatBis { get; set; }
        public decimal preisProzent { get; set; }
    }
}
