//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpenstern_BackEnd_Neu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmerbuchung
    {
        public int id { get; set; }
        public int zimmer_id { get; set; }
        public int mitarbeiter_id { get; set; }
        public int kategorieanfrage_id { get; set; }
        public Nullable<bool> checkedStatus { get; set; }
    
        public virtual Kategorieanfrage Kategorieanfrage { get; set; }
        public virtual Mitarbeiter Mitarbeiter { get; set; }
        public virtual Zimmer Zimmer { get; set; }
    }
}
